const swaggerAutogen = require('swagger-autogen')()

const doc = {
    info: {
        version: "1.0.0",
        title: "Documentation",
        description: "Docs automatically generated by the <b>Sirojiddin's auto docs</b> module."
    },
    host: "95.130.227.93:5000",
    schemes: ['https', 'http'],
    components: {
        securitySchemes: {
            bearerAuth: {
                type: 'https',
                scheme: 'bearer'
            }
        }
    },
    securityDefinitions: {
        apiKeyAuth: {
            type: 'apiKey',
            in: 'header', // can be 'header', 'query' or 'cookie'
            name: 'Authorization', // name of the header, query parameter or cookie
        }
    },
}

const outputFile = './swagger-output.json';
const endpointsFiles = ['./server.js']; // Path to your routes files
// const endpointsFiles = ['./routes/*.js']; // Path to your routes files

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./server.js') // Your project's root file
})