const swaggerAutogen = require('swagger-autogen')();

const doc = {
    info: {
        version: "1.0.0",
        title: "Documentation",
        description: "Docs automatically generated by the <b>Shoxrux's auto docs</b> module."
    },
    host: "10.100.26.2:5050", // Protokolsiz domen nomi
    schemes: ['http', 'https'], // Qo'llab-quvvatlanadigan protokollar
    components: {
        securitySchemes: {
            bearerAuth: {
                type: 'http',
                scheme: 'bearer', // Bearer tokenni belgilash
            }
        }
    },
    securityDefinitions: {
        apiKeyAuth: {
            type: 'apiKey',
            in: 'header', // Authorization header sifatida
            name: 'Authorization', // Header nomi
        }
    },
};

const outputFile = './swagger-output.json';
const endpointsFiles = ['./server.js']; // Asosiy yo'nalishlar fayli

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./server.js'); // Serverni ishga tushirish
});
